Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 731, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 386, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 316, in async_add_job
    task = self.loop.create_task(target(*args))
TypeError: stop() takes 1 positional argument but 2 were given
2020-09-13 09:50:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.under_stairs_led
2020-09-13 09:50:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.cloakroom_led
2020-09-13 09:50:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.under_stairs_light
Client error on /homeassistant/restart request 
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[09:50:40] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-09-13 09:50:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-13 09:50:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-13 09:50:52 WARNING (MainThread) [homeassistant.components.template] Template sensor 'unavailable_entities' has no entity ids configured to track nor were we able to extract the entities to track from the value, matched_devices template(s). This entity will only be able to be updated manually
2020-09-13 10:46:11 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_stop[L]>) at /usr/src/homeassistant/homeassistant/core.py:719
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 731, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 386, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 316, in async_add_job
    task = self.loop.create_task(target(*args))
TypeError: stop() takes 1 positional argument but 2 were given
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
Client error on /homeassistant/restart request 
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[10:46:25] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-09-13 10:46:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-13 10:46:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-13 10:46:38 WARNING (MainThread) [homeassistant.components.template] Template sensor 'unavailable_entities' has no entity ids configured to track nor were we able to extract the entities to track from the value, matched_devices template(s). This entity will only be able to be updated manually
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
2020-09-13 10:50:15 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_stop[L]>) at /usr/src/homeassistant/homeassistant/core.py:719
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 731, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 386, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 316, in async_add_job
    task = self.loop.create_task(target(*args))
TypeError: stop() takes 1 positional argument but 2 were given
2020-09-13 10:50:15 WARNING (MainThread) [homeassistant.components.automation.system_low_battery_warning] System - Low Battery Warning: Already running
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[10:56:08] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-09-13 10:56:19 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-13 10:56:19 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-13 10:56:25 WARNING (MainThread) [homeassistant.components.template] Template sensor 'unavailable_entities' has no entity ids configured to track nor were we able to extract the entities to track from the value, matched_devices template(s). This entity will only be able to be updated manually
2020-09-13 10:57:00 WARNING (MainThread) [homeassistant.components.alexa.capabilities] Invalid temp value None for sensor.under_stairs_temperature
2020-09-13 10:57:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.under_stairs_led
2020-09-13 10:57:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.cloakroom_led
2020-09-13 10:57:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.under_stairs_light
2020-09-13 10:57:15 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-09-13 10:57:30 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.under_stairs_led
2020-09-13 10:57:30 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.cloakroom_led
2020-09-13 10:57:30 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.under_stairs_light